# Generated by Django 5.0.6 on 2024-05-29 15:08

import autoslug.fields
import django.db.models.deletion
import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=forum.models.get_slug, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ('created_at',),
                'default_related_name': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=forum.models.get_slug, unique=True)),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'Темы',
                'ordering': ('-created_at',),
                'default_related_name': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=forum.models.get_slug, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'форум',
                'verbose_name_plural': 'Форумы',
                'ordering': ('title',),
                'default_related_name': 'forums',
            },
        ),
    ]
