# Generated by Django 5.0.6 on 2024-06-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topic_description_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
    ]
