# Generated by Django 5.0.6 on 2024-05-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='favorite_games',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='любимые игры'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='favorite_genres',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='любимые жанры'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='местоположение'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='nickname',
            field=models.CharField(max_length=150, unique=True, verbose_name='никнейм'),
        ),
    ]
